#!/usr/bin/python
import sys
from curses.ascii import isdigit 
from nltk.corpus import cmudict # get the CMU Pronouncing Dict
import requests # python-requests is awesome
import re

#pass the session_id as first parameter
session_id = sys.argv[1]

#function for calculating number of syllables in a word
d = cmudict.dict() 
def number_of_syllables_in_word(word): 
    word = re.sub(ur'[\W_]+',u'',word) #remove non-alpha chars
    """return the max syllable count in the case of multiple pronunciations"""
    return max([len([y for y in x if isdigit(y[-1])]) for x in d[word.lower()]])
    
#request the transcript as plain text and split to sentences    
url = "http://asciiwwdc.com/2013/sessions/%s" % session_id
r = requests.get(url,headers={"Accept":"text/plain"})
lines = r.text.split(".")


FIRST_LINE = 5
SECOND_LINE = 5+7
THIRD_LINE = 5+7+5

possiblehaikus = []
for l in lines:
    haiku = "" #this will store our formatted haiku
    l = l.strip()
    words = l.split(" ")
    syl_count = 0
    try:
        wordboundaries = []
        for word in words:
            syl_count+=number_of_syllables_in_word(word)
            haiku+=word
            haiku+=" "
            wordboundaries.append(syl_count)
            if syl_count==FIRST_LINE or syl_count==SECOND_LINE or syl_count==THIRD_LINE:
                haiku+="\n"
        if syl_count==THIRD_LINE and FIRST_LINE in wordboundaries and SECOND_LINE in wordboundaries:
            print haiku+"\n"
            
    except KeyError:
        pass
